# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6dd85884e18e62c5158eace34882b30667fa08f6f9e9d7957858232b32276684a4cf7726c95d1f9b07ecf2b8a58b12a1f4e2fb8e102bee8482cd647578df060

test:
  secret_key_base: 8acd4941e18f5d5d5a9f826007747422bd3299f72082a89a48cac1b26df70c10430e85f17d453f34407de7cd20d9e1087ca7fe69bae0137ef15c62e2c93949c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
